import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Check, CheckCircle2, Clock3, CreditCard, ArrowRight } from 'lucide-react';
import { checkoutPreview } from '../../stores/preview';
import { useAction, useCart, useOrder } from '../../hooks/preview';
import { Amount, Badge, Confirm, ErrorState, Loading } from '../../components/ui/common';
import { ProductArt } from '../../components/ui/ProductArt';

import type { Order } from '../../types/ui';
export function OrderSummary({ order, prefix }: { order: Order; prefix: 'checkout' | 'success' | 'order-detail' }) { return <><div className="order-lines">{order.lines.map((line) => <div className="order-line" key={line.productId} data-testid={`${prefix === 'order-detail' ? 'order' : prefix}-line-${line.productId}`}><ProductArt id={line.productId} small/><div><h3>{line.name}</h3><span><Amount testId={prefix === 'order-detail' ? 'order-line-unit-price' : undefined} value={line.price}/> × <span data-testid={prefix === 'order-detail' ? 'order-line-qty' : undefined} data-value={line.quantity}>{line.quantity}</span></span></div><Amount value={line.lineTotal}/></div>)}</div><div className="order-totals"><div className="summary-row"><span>Subtotal</span><Amount testId={`${prefix}-subtotal`} value={order.subtotal}/></div><div className="summary-row"><span>Discount{order.couponCode ? ` (${order.couponCode})` : ''}</span><Amount testId={`${prefix}-discount`} value={order.discount}/></div><div className="summary-row"><span>Shipping</span><Amount testId={`${prefix}-shipping`} value={order.shipping}/></div><div className="summary-row total"><strong>Total</strong><Amount testId={`${prefix}-total`} value={order.total}/></div></div><div className="delivery-detail"><span>Delivery zone<strong>{{ inCity: 'In city', upcountry: 'Upcountry', remote: 'Remote area' }[order.zone]}</strong></span><span>Delivery speed<strong>{order.speed === 'express' ? 'Express' : 'Standard'}</strong></span></div></>; }
export function CheckoutPage({ success = false }: { success?: boolean }) { const { data: cart, error: cartError, refetch: refetchCart } = useCart(); const { data: order, error, refetch } = useOrder(cart?.currentOrderId ?? null); const [confirm, setConfirm] = useState(false); const navigate = useNavigate(); const cancel = useAction(checkoutPreview.cancel, () => navigate('/cart')); const next = useAction(checkoutPreview.continue, () => navigate('/products')); const [search] = useSearchParams(); const failed = search.get('state') === 'failed'; if (cartError) return <ErrorState error={cartError} retry={() => void refetchCart()}/>; if (error) return <ErrorState error={error} retry={() => void refetch()}/>; if (!order) return <Loading rows={1}/>; return <main className="checkout-page" data-testid={success ? 'page-success' : 'page-checkout'}><div className="checkout-steps"><span><Check size={14}/>Your bag</span><span className={!success ? 'current' : ''}>{success ? <Check size={14}/> : '02'}Payment</span><span className={success ? 'current' : ''}>03 Complete</span></div><div className="checkout-title">{success ? <CheckCircle2 size={44}/> : <Clock3 size={40}/>}<span className="eyebrow">{success ? 'A NEW RITUAL IS ON ITS WAY' : 'CHECKOUT SCREEN PREVIEW'}</span><h1>{success ? 'A good morning awaits.' : 'One step closer to your ritual.'}</h1><p>{success ? 'Success screen preview. No payment has been processed.' : 'Illustrative order and sample totals. No order has been placed.'}</p></div><section className="order-card"><div className="order-card-heading"><div><span className="eyebrow">ORDER REFERENCE</span><h2 data-testid={`${success ? 'success' : 'checkout'}-order-id`}>{order.orderId}</h2></div><Badge status={success ? 'paid' : 'pending'}/></div><OrderSummary order={order} prefix={success ? 'success' : 'checkout'}/>{!success && <div className="payment-state"><CreditCard size={21}/><div><strong>{failed ? 'Payment failed' : 'Awaiting payment'}</strong><p>{failed ? 'การชำระเงินล้มเหลว กรุณาลองใหม่' : 'This is the pending payment state shown for UI review.'}</p></div></div>}<div className="order-actions">{success ? <button className="btn primary" data-testid="continue-shopping-button" disabled={next.isPending} onClick={() => next.mutate(undefined)}>Continue shopping <ArrowRight size={17}/></button> : <button className="btn" data-testid="cancel-checkout-button" onClick={() => setConfirm(true)}>Cancel checkout</button>}</div></section><aside className="preview-states"><strong>Preview screens</strong><Link className="btn" to="/checkout">Pending</Link><Link className="btn" to="/checkout?state=failed">Failure</Link><Link className="btn" to="/success">Success</Link></aside>{confirm && <Confirm title="Cancel checkout?" pending={cancel.isPending} onClose={() => setConfirm(false)} onConfirm={() => cancel.mutate(undefined)}>Return to the bag screen. This UI preview does not manage stock reservations.</Confirm>}</main>; }
