import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Package, Save, Ticket } from 'lucide-react';
import { adminApi } from './api';
import { productApi } from '../products/api';
import { useAction, useSession } from '../../hooks/queries';
import { useUI } from '../../stores/ui';
import { Amount, Badge, Confirm, Empty, ErrorState, Loading } from '../../components/ui/common';
import { ProductArt } from '../../components/ui/ProductArt';
import type { Coupon, Product, SaleStatus } from '../../types/api';
export const productSchema = z.object({ price: z.number().int('Enter a whole-number price.').min(1, 'Price must be 1–50,000.').max(50000, 'Price must be 1–50,000.'), stock: z.number().int('Enter whole-number stock.').min(0, 'Stock must be 0–9,999.').max(9999, 'Stock must be 0–9,999.') });
function ProductRow({ product }: { product: Product }) { const [confirm, setConfirm] = useState(false); const { register, handleSubmit, formState: { errors } } = useForm<z.infer<typeof productSchema>>({ resolver: zodResolver(productSchema), values: { price: product.price, stock: product.stock } }); const save = useAction((data: z.infer<typeof productSchema>) => adminApi.update(product.productId, data), () => useUI.getState().notify({ kind: 'info', code: '', message: `${product.name} updated.` })); const status = useAction((next: SaleStatus) => adminApi.setProductStatus(product.productId, { status: next }), () => setConfirm(false)); return <tr data-testid={`admin-product-row-${product.productId}`}><td><div className="admin-product-name"><ProductArt id={product.productId} small /><div><strong>{product.name}</strong><small>{product.productId} · {product.weightGram.toLocaleString()} g</small></div></div></td><td><Amount value={product.price} testId="admin-product-price" /><form id={`edit-${product.productId}`} onSubmit={handleSubmit((data) => save.mutate(data))} noValidate><label className="sr-only" htmlFor={`price-${product.productId}`}>Price for {product.name}</label><input id={`price-${product.productId}`} data-testid="admin-product-price-input" type="number" min="1" max="50000" step="1" {...register('price', { valueAsNumber: true })} aria-invalid={!!errors.price} />{errors.price && <p className="field-error">{errors.price.message}</p>}</form></td><td><Amount value={product.stock} testId="admin-product-stock">{product.stock} available</Amount><label className="sr-only" htmlFor={`stock-${product.productId}`}>Stock for {product.name}</label><input id={`stock-${product.productId}`} data-testid="admin-product-stock-input" form={`edit-${product.productId}`} type="number" min="0" max="9999" step="1" {...register('stock', { valueAsNumber: true })} aria-invalid={!!errors.stock} />{errors.stock && <p className="field-error">{errors.stock.message}</p>}</td><td><Badge status={product.status} testId="admin-product-status" /><button className="text-link" data-testid="admin-product-toggle-status" disabled={status.isPending} onClick={() => setConfirm(true)}>{product.status === 'enabled' ? 'Disable sales' : 'Enable sales'}</button>{confirm && <Confirm title={`${product.status === 'enabled' ? 'Disable' : 'Enable'} product sales?`} pending={status.isPending} onClose={() => setConfirm(false)} onConfirm={() => status.mutate(product.status === 'enabled' ? 'disabled' : 'enabled')}>{product.name}: this changes availability for customer carts. Existing order snapshots remain unchanged.</Confirm>}</td><td><button form={`edit-${product.productId}`} className="btn" data-testid="admin-product-save" disabled={save.isPending || status.isPending} type="submit"><Save size={15} />{save.isPending ? 'Saving…' : 'Save changes'}</button></td></tr>; }
function CouponRow({ coupon }: { coupon: Coupon }) { const [confirm, setConfirm] = useState(false); const toggle = useAction((status: SaleStatus) => adminApi.setCouponStatus(coupon.code, { status }), () => setConfirm(false)); return <tr data-testid={`admin-coupon-row-${coupon.code}`}><td><strong className="coupon-code"><Ticket size={17} />{coupon.code}</strong></td><td><Amount value={coupon.percent} testId="admin-coupon-percent">{coupon.percent}%</Amount></td><td><Amount value={coupon.minSpend} testId="admin-coupon-min-spend" /></td><td><Badge status={coupon.status} testId="admin-coupon-status" /></td><td><button className="btn" data-testid="admin-coupon-toggle-status" onClick={() => setConfirm(true)} disabled={toggle.isPending}>{coupon.status === 'enabled' ? 'Disable coupon' : 'Enable coupon'}</button>{confirm && <Confirm title={`${coupon.status === 'enabled' ? 'Disable' : 'Enable'} ${coupon.code}?`} pending={toggle.isPending} onClose={() => setConfirm(false)} onConfirm={() => toggle.mutate(coupon.status === 'enabled' ? 'disabled' : 'enabled')}>This change takes effect at the next checkout. Existing orders retain their recorded discount.</Confirm>}</td></tr>; }
export function AdminProductsPage() { const { data: user } = useSession(); const products = useQuery({ queryKey: ['products', user?.username], queryFn: ({ signal }) => productApi.list(signal), refetchInterval: 5000 }); return <main data-testid="page-admin-products"><AdminHeading title="Product management" description="A considered collection, carefully managed." /><div className="admin-note"><Package size={19} /><p>Edit prices and available stock, or manage sales status. All products are pre-seeded.</p></div>{products.isLoading ? <Loading /> : products.error ? <ErrorState error={products.error} retry={() => void products.refetch()} /> : !products.data?.length ? <Empty title="No products returned" /> : <div className="table-scroll" data-testid="admin-product-table"><table className="admin-table"><thead><tr><th>Product</th><th>Price (THB)</th><th>Available stock</th><th>Sales status</th><th>Changes</th></tr></thead><tbody>{products.data.map((product) => <ProductRow key={product.productId} product={product} />)}</tbody></table></div>}</main>; }
export function AdminCouponsPage() { const coupons = useQuery({ queryKey: ['coupons'], queryFn: ({ signal }) => adminApi.coupons(signal) }); return <main data-testid="page-admin-coupons"><AdminHeading title="Coupon management" description="Little rewards for everyday rituals." /><div className="admin-note"><Ticket size={19} /><p>Manage coupon availability. Discount percentages and minimum spend are defined by the store.</p></div>{coupons.isLoading ? <Loading /> : coupons.error ? <ErrorState error={coupons.error} retry={() => void coupons.refetch()} /> : !coupons.data?.length ? <Empty title="No coupons returned" /> : <div className="table-scroll" data-testid="admin-coupon-table"><table><thead><tr><th>Coupon code</th><th>Discount</th><th>Minimum spend</th><th>Status</th><th>Manage</th></tr></thead><tbody>{coupons.data.map((coupon) => <CouponRow key={coupon.code} coupon={coupon} />)}</tbody></table></div>}</main>; }
function AdminHeading({ title, description }: { title: string; description: string }) { return <div className="page-heading"><span className="eyebrow">STORE ADMINISTRATION</span><h1>{title}</h1><p>{description}</p></div>; }
