import { useEffect, useRef } from 'react';
import type { ReactNode } from 'react';
import { AlertCircle, ArrowRight, Check, Coffee, Minus, Plus, X } from 'lucide-react';
import { useUI } from '../../stores/ui';
import { errorMessage } from '../../data/errors';

const money = (value: number) => new Intl.NumberFormat('en-TH', { style: 'currency', currency: 'THB', maximumFractionDigits: 0 }).format(value);
export function Amount({ value, testId, children }: { value: number; testId?: string; children?: ReactNode }) { return <span data-testid={testId} data-value={value}>{children ?? money(value)}</span>; }
export function Badge({ status, testId }: { status: string; testId?: string }) { return <span className={`badge ${status}`} data-testid={testId} data-status={status}><span className="status-dot"/>{({ enabled: 'Enabled', disabled: 'Disabled', pending: 'Awaiting payment', paid: 'Paid', cancelled: 'Cancelled' } as Record<string, string>)[status] || status}</span>; }
export function AppMessage() { const message = useUI((s) => s.message); const notify = useUI((s) => s.notify); if (!message) return null; return <div className={`app-message ${message.kind}`} data-testid="app-message" data-kind={message.kind} data-code={message.code} role={message.kind === 'error' ? 'alert' : 'status'}><AlertCircle size={19}/><div>{message.message}{message.code && <small>{message.code}</small>}{!!message.fields?.length && <small>Fields: {message.fields.join(', ')}</small>}{!!message.productIds?.length && <small>Products: {message.productIds.join(', ')}</small>}</div><button onClick={() => notify(null)} aria-label="Dismiss message"><X size={18}/></button></div>; }
export function Loading({ rows = 3 }: { rows?: number }) { return <div role="status" aria-label="Loading" className="skeleton-grid">{Array.from({ length: rows }, (_, i) => <div key={i} className="skeleton"/>)}<span className="sr-only">Loading…</span></div>; }
export function ErrorState({ error, retry }: { error: unknown; retry: () => void }) { const e = errorMessage(error); return <div className="empty-state" role="alert"><AlertCircle size={30}/><h2>{e.code === 'ORDER_NOT_FOUND' ? 'Order not found' : 'We couldn’t load this page'}</h2><div data-testid="app-message" data-kind="error" data-code={e.code}><p>{e.message}</p><small>{e.code}</small></div><button className="btn primary" onClick={retry}>Try again <ArrowRight size={16}/></button></div>; }
export function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="empty-state"><Coffee size={35}/><h2>{title}</h2>{children}</div>; }
export function Quantity({ value, onChange, id, testId, disabled = false }: { value: number; onChange: (value: number) => void; id: string; testId: string; disabled?: boolean }) { return <div className="quantity"><button type="button" aria-label="Decrease quantity" disabled={disabled || value <= 1} onClick={() => onChange(value - 1)}><Minus size={14}/></button><label htmlFor={id} className="sr-only">Quantity</label><input id={id} data-testid={testId} type="number" min="1" max="10" step="1" value={Number.isNaN(value) ? '' : value} onChange={(e) => onChange(e.target.valueAsNumber)} disabled={disabled}/><button type="button" aria-label="Increase quantity" disabled={disabled || value >= 10 || Number.isNaN(value)} onClick={() => onChange(value + 1)}><Plus size={14}/></button></div>; }
export function Confirm({ title, children, onConfirm, onClose, pending }: { title: string; children: ReactNode; onConfirm: () => void; onClose: () => void; pending?: boolean }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { ref.current?.showModal(); const dialog = ref.current; return () => dialog?.close(); }, []); return <dialog ref={ref} onCancel={(e) => { e.preventDefault(); if (!pending) onClose(); }} aria-labelledby="confirm-title"><div className="dialog-content"><h2 id="confirm-title">{title}</h2><p>{children}</p><div className="dialog-actions"><button className="btn" disabled={pending} onClick={onClose}>Keep as is</button><button className="btn primary" disabled={pending} onClick={onConfirm}>{pending ? 'Working…' : 'Confirm'}<Check size={16}/></button></div></div></dialog>; }

