import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Leaf, PackageCheck, ShoppingBag } from 'lucide-react';
import { productApi } from './api';
import { cartApi } from '../cart/api';
import { useAction, useCart, useSession } from '../../hooks/queries';
import { useUI } from '../../stores/ui';
import type { Product } from '../../types/api';
import { Amount, Empty, ErrorState, Loading, Quantity } from '../../components/ui/common';
import { ProductArt } from '../../components/ui/ProductArt';
const editorial: Record<string, { category: string; detail: string }> = { P1: { category: 'THE DAILY ESSENTIAL', detail: 'Your morning, made a little more intentional.' }, P2: { category: 'PRECISION IN EVERY POUR', detail: 'Slow down. A great cup is worth the ritual.' }, P3: { category: 'YOUR HOME COFFEE BAR', detail: 'Bring the café experience to your countertop.' } };
export function ProductCard({ product, locked = false }: { product: Product; locked?: boolean }) { const [quantity, setQuantity] = useState(1); const [added, setAdded] = useState(false); const add = useAction(cartApi.add, () => { setAdded(true); useUI.getState().notify({ kind: 'info', code: '', message: `${product.name} added to your bag.` }); }); const meta = editorial[product.productId]; return <article className="product-card" data-testid={`product-row-${product.productId}`}><div className="product-visual"><ProductArt id={product.productId}/><span className="product-tag">{product.productId === 'P1' ? 'Daily favorite' : product.productId === 'P2' ? 'The perfect pour' : 'Café at home'}</span></div><div className="product-body"><span className="eyebrow">{meta?.category || 'RITUAL ESSENTIAL'}</span><div className="product-title"><h3 data-testid="product-name">{product.name}</h3><Amount testId="product-price" value={product.price}/></div><p>{meta?.detail || 'Thoughtfully selected for your daily routine.'}</p><div className="product-facts"><span><span className="stock-dot"/><Amount testId="product-stock" value={product.stock}>{product.stock} in stock</Amount></span><span>{product.weightGram.toLocaleString()} g</span></div><div className="product-controls"><Quantity id={`add-${product.productId}`} testId="product-add-qty" value={quantity} onChange={(v) => { setQuantity(v); setAdded(false); }} disabled={locked || add.isPending}/><button className="btn primary" data-testid="product-add-button" disabled={locked || add.isPending || !Number.isInteger(quantity) || quantity < 1 || quantity > 10} onClick={() => add.mutate({ productId: product.productId, quantity })}>{add.isPending ? 'Adding…' : added ? 'Add again' : 'Add to bag'}{added ? <Check size={16}/> : <ShoppingBag size={16}/>}</button></div></div></article>; }
export function ProductsPage() { const { data: user } = useSession(); const { data: cart } = useCart(); const products = useQuery({ queryKey: ['products', user?.username], queryFn: ({ signal }) => productApi.list(signal), refetchInterval: 5000 }); return <main data-testid="page-products"><section className="shop-hero"><div><span className="eyebrow">THE EVERYDAY COLLECTION / 01</span><h1>Small rituals.<br/><em>Better mornings.</em></h1><p>Good coffee starts with the essentials.<br/>Discover a considered collection for your daily cup.</p><a href="#collection" className="text-link">Find your next ritual <ArrowRight size={17}/></a></div><div className="hero-art"><span className="hero-circle"/><ProductArt id="P2"/><div className="hero-caption"><span>THE ART OF SLOWING DOWN</span><small>One cup at a time.</small></div><span className="hero-number">01 — 03</span></div></section><section id="collection" className="collection"><div className="section-heading"><div><span className="eyebrow">THOUGHTFULLY SELECTED</span><h2>Meet your new essentials.</h2></div><span>{products.data?.length ?? '…'} essentials <span className="muted">/ Made for every day</span></span></div>{products.isLoading ? <Loading/> : products.error ? <ErrorState error={products.error} retry={() => void products.refetch()}/> : !products.data?.length ? <Empty title="No essentials available right now"><p>Check back soon for available products.</p></Empty> : <div className="product-grid">{products.data.map((product) => <ProductCard key={product.productId} product={product} locked={cart?.stage !== 'cart'}/>)}</div>}</section><section className="values-strip"><div><Leaf size={24}/><span><strong>Considered essentials</strong><small>Everything you need for your daily cup.</small></span></div><div><PackageCheck size={24}/><span><strong>Delivered your way</strong><small>Choose your zone and delivery speed.</small></span></div><div><ShoppingBag size={24}/><span><strong>A ritual worth keeping</strong><small><Link to="/cart">Your next great morning starts in your bag.</Link></small></span></div></section></main>; }
