import { useState } from 'react';

import { Link } from 'react-router-dom';
import { ArrowRight, Check, Package, PackageCheck, ShoppingBag } from 'lucide-react';

import { bagPreview } from '../../stores/preview';
import { useAction, useProducts } from '../../hooks/preview';
import { useUI } from '../../stores/ui';
import type { Product } from '../../types/ui';
import { Amount, Empty, ErrorState, Loading, Quantity } from '../../components/ui/common';
import { ProductArt } from '../../components/ui/ProductArt';
const editorial: Record<string, { category: string; detail: string }> = { P1: { category: 'PRODUCT INFORMATION', detail: 'View current pricing, stock, and shipping weight below.' }, P2: { category: 'PRODUCT INFORMATION', detail: 'Choose your quantity and add this product to your cart.' }, P3: { category: 'PRODUCT INFORMATION', detail: 'Check availability and choose the quantity you need.' } };
export function ProductCard({ product }: { product: Product }) { const [quantity, setQuantity] = useState(1); const [added, setAdded] = useState(false); const add = useAction(bagPreview.add, () => { setAdded(true); useUI.getState().notify({ kind: 'info', code: '', message: `${product.name} added to your bag.` }); }); const meta = editorial[product.productId]; return <article className="product-card" data-testid={`product-row-${product.productId}`}><div className="product-visual"><ProductArt id={product.productId}/><span className="product-tag">{product.productId}</span></div><div className="product-body"><span className="eyebrow">{meta?.category || 'PRODUCT INFORMATION'}</span><div className="product-title"><h3 data-testid="product-name">{product.name}</h3><Amount testId="product-price" value={product.price}/></div><p>{meta?.detail || 'View the product information below.'}</p><div className="product-facts"><span><span className="stock-dot"/><Amount testId="product-stock" value={product.stock}>{product.stock} in stock</Amount></span><span>{product.weightGram.toLocaleString()} g</span></div><div className="product-controls"><Quantity id={`add-${product.productId}`} testId="product-add-qty" value={quantity} onChange={(v) => { setQuantity(v); setAdded(false); }} disabled={add.isPending}/><button className="btn primary" data-testid="product-add-button" disabled={add.isPending} onClick={() => add.mutate({ productId: product.productId, quantity })}>{add.isPending ? 'Adding…' : added ? 'Add again' : 'Add to cart'}{added ? <Check size={16}/> : <ShoppingBag size={16}/>}</button></div></div></article>; }
export function ProductsPage() { const products = useProducts(); return <main data-testid="page-products"><section className="shop-hero"><div><span className="eyebrow">EXPLORE ORBIT MARKET</span><h1>Everyday finds.<br/><em>All in one place.</em></h1><p>Explore our catalog and find your next purchase.<br/>Current prices. Clear availability. Your choice.</p><a href="#collection" className="text-link">Browse products <ArrowRight size={17}/></a></div><div className="hero-art"><span className="hero-circle"/><div className="market-hero-illustration" aria-hidden="true"><div className="hero-parcel"><Package size={96} strokeWidth={1.2}/></div><div className="hero-basket"><ShoppingBag size={72} strokeWidth={1.4}/></div><span className="hero-orbit"/></div><div className="hero-caption"><span>YOUR EVERYDAY MARKETPLACE</span><small>Discover. Choose. Enjoy.</small></div><span className="hero-number">ORBIT / MARKET</span></div></section><section id="collection" className="collection"><div className="section-heading"><div><span className="eyebrow">SHOP THE CATALOG</span><h2>Explore our products.</h2></div><span>{products.data?.length ?? '…'} products <span className="muted">/ Available now</span></span></div>{products.isLoading ? <Loading/> : products.error ? <ErrorState error={products.error} retry={() => void products.refetch()}/> : !products.data?.length ? <Empty title="No products available right now"><p>Check back soon for available products.</p></Empty> : <div className="product-grid">{products.data.map((product) => <ProductCard key={product.productId} product={product}/>)}</div>}</section><section className="values-strip"><div><Package size={24}/><span><strong>Products at a glance</strong><small>See current prices and available stock.</small></span></div><div><PackageCheck size={24}/><span><strong>Delivered your way</strong><small>Choose your zone and delivery speed.</small></span></div><div><ShoppingBag size={24}/><span><strong>Your cart, your choices</strong><small><Link to="/cart">Review your products before checkout.</Link></small></span></div></section></main>; }
